ALTER TABLE car ADD COLUMN IF NOT EXISTS catalog_price_cents BIGINT;
ALTER TABLE car ADD COLUMN IF NOT EXISTS used_value_cents BIGINT;
ALTER TABLE car ADD COLUMN IF NOT EXISTS selling_price_cents BIGINT;
