export interface ColorOption { name: string; hex: string }

export const CAR_COLORS: ColorOption[] = [
  { name: 'Black', hex: '#1a1a1a' },
  { name: 'White', hex: '#f5f5f5' },
  { name: 'Silver', hex: '#c0c0c0' },
  { name: 'Grey', hex: '#808080' },
  { name: 'Anthracite', hex: '#383838' },
  { name: 'Blue', hex: '#1d4ed8' },
  { name: 'Dark Blue', hex: '#1e3a5f' },
  { name: 'Light Blue', hex: '#7dd3fc' },
  { name: 'Red', hex: '#dc2626' },
  { name: 'Dark Red', hex: '#7f1d1d' },
  { name: 'Green', hex: '#16a34a' },
  { name: 'Dark Green', hex: '#14532d' },
  { name: 'Brown', hex: '#78350f' },
  { name: 'Beige', hex: '#d4c5a9' },
  { name: 'Yellow', hex: '#eab308' },
  { name: 'Orange', hex: '#ea580c' },
  { name: 'Gold', hex: '#b8860b' },
  { name: 'Navy', hex: '#1e3a5f' },
  { name: 'Burgundy', hex: '#800020' },
  { name: 'Purple', hex: '#7c3aed' },
  { name: 'Champagne', hex: '#f7e7ce' },
  { name: 'Bronze', hex: '#cd7f32' },
]

export const TRIM_COLORS: ColorOption[] = [
  { name: 'Black', hex: '#1a1a1a' },
  { name: 'Dark Grey', hex: '#4a4a4a' },
  { name: 'Light Grey', hex: '#b0b0b0' },
  { name: 'Beige', hex: '#d4c5a9' },
  { name: 'Cream', hex: '#fffdd0' },
  { name: 'Brown', hex: '#78350f' },
  { name: 'Cognac', hex: '#9a4e1c' },
  { name: 'Tan', hex: '#d2b48c' },
  { name: 'Red', hex: '#dc2626' },
  { name: 'Burgundy', hex: '#800020' },
  { name: 'White', hex: '#f5f5f5' },
  { name: 'Blue', hex: '#1d4ed8' },
  { name: 'Carbon', hex: '#2d2d2d' },
  { name: 'Alcantara Black', hex: '#282828' },
  { name: 'Alcantara Grey', hex: '#707070' },
]

export interface ModelInfo {
  versions: string[]
}

export const CAR_MAKES_MODELS: Record<string, Record<string, ModelInfo>> = {
  'Abarth': {
    '595': { versions: ['Base', 'Turismo', 'Competizione', 'Esseesse'] },
    '695': { versions: ['Anniversary', 'Rivale', 'Biposto'] },
    '500e': { versions: ['Scorpionissima'] },
  },
  'Alfa Romeo': {
    'Giulia': { versions: ['Sprint', 'Ti', 'Veloce', 'Quadrifoglio'] },
    'Stelvio': { versions: ['Sprint', 'Ti', 'Veloce', 'Quadrifoglio'] },
    'Tonale': { versions: ['Sprint', 'Ti', 'Veloce', 'PHEV'] },
    'Giulietta': { versions: ['Super', 'Sprint', 'Veloce'] },
    '33 Stradale': { versions: ['Stradale'] },
  },
  'Alpine': {
    'A110': { versions: ['Pure', 'Légende', 'S', 'R'] },
    'A290': { versions: ['GT', 'GTS'] },
  },
  'Aston Martin': {
    'DB12': { versions: ['Coupe', 'Volante'] },
    'Vantage': { versions: ['Coupe', 'Roadster'] },
    'DBX': { versions: ['DBX', 'DBX707'] },
    'DBS': { versions: ['Coupe', 'Volante'] },
  },
  'Audi': {
    'A1': { versions: ['Sportback', 'S line'] },
    'A3': { versions: ['Sportback', 'Sedan', 'S line', 'TFSI e'] },
    'A4': { versions: ['Sedan', 'Avant', 'S line', 'allroad'] },
    'A5': { versions: ['Coupe', 'Sportback', 'Cabriolet', 'S line'] },
    'A6': { versions: ['Sedan', 'Avant', 'S line', 'allroad', 'TFSI e'] },
    'A7': { versions: ['Sportback', 'S line', 'TFSI e'] },
    'A8': { versions: ['Standard', 'Long', 'S line', 'TFSI e'] },
    'Q2': { versions: ['Standard', 'S line', 'Edition One'] },
    'Q3': { versions: ['Standard', 'Sportback', 'S line'] },
    'Q5': { versions: ['Standard', 'Sportback', 'S line', 'TFSI e'] },
    'Q7': { versions: ['Standard', 'S line', 'TFSI e'] },
    'Q8': { versions: ['Standard', 'S line'] },
    'Q4 e-tron': { versions: ['35', '40', '45', '50', 'Sportback'] },
    'e-tron GT': { versions: ['Standard', 'RS'] },
    'RS3': { versions: ['Sportback', 'Sedan'] },
    'RS4': { versions: ['Avant'] },
    'RS5': { versions: ['Coupe', 'Sportback'] },
    'RS6': { versions: ['Avant', 'Performance'] },
    'RS7': { versions: ['Sportback', 'Performance'] },
    'RSQ8': { versions: ['Standard', 'Performance'] },
    'S3': { versions: ['Sportback', 'Sedan'] },
    'TT': { versions: ['Coupe', 'Roadster', 'TTS', 'TTRS'] },
    'R8': { versions: ['Coupe', 'Spyder', 'Performance'] },
  },
  'Bentley': {
    'Continental GT': { versions: ['V8', 'Speed', 'Mulliner'] },
    'Flying Spur': { versions: ['V8', 'W12', 'Mulliner'] },
    'Bentayga': { versions: ['V8', 'S', 'EWB'] },
  },
  'BMW': {
    '1 Series': { versions: ['116i', '118i', '120i', 'M135i', 'M Sport'] },
    '2 Series': { versions: ['Coupe', 'Gran Coupe', 'Active Tourer', 'M Sport', 'M240i'] },
    '3 Series': { versions: ['318i', '320i', '330i', '330e', '320d', 'M Sport', 'M340i'] },
    '4 Series': { versions: ['Coupe', 'Convertible', 'Gran Coupe', 'M Sport', 'M440i'] },
    '5 Series': { versions: ['520i', '530i', '530e', '520d', '540i', 'M Sport', 'M550i'] },
    '7 Series': { versions: ['735i', '740i', '760i', 'M Sport', 'i7'] },
    '8 Series': { versions: ['Coupe', 'Convertible', 'Gran Coupe', 'M850i'] },
    'X1': { versions: ['sDrive18i', 'xDrive23i', 'xDrive25e', 'M Sport'] },
    'X2': { versions: ['sDrive18i', 'xDrive25e', 'M Sport', 'M35i'] },
    'X3': { versions: ['xDrive20i', 'xDrive30i', 'xDrive30e', 'M Sport', 'M40i'] },
    'X4': { versions: ['xDrive20i', 'xDrive30i', 'M Sport', 'M40i'] },
    'X5': { versions: ['xDrive40i', 'xDrive45e', 'xDrive50e', 'M Sport', 'M60i'] },
    'X6': { versions: ['xDrive40i', 'M Sport', 'M60i'] },
    'X7': { versions: ['xDrive40i', 'xDrive40d', 'M Sport', 'M60i'] },
    'XM': { versions: ['Standard', 'Label Red'] },
    'Z4': { versions: ['sDrive20i', 'sDrive30i', 'M40i'] },
    'M2': { versions: ['Standard'] },
    'M3': { versions: ['Sedan', 'Touring', 'Competition'] },
    'M4': { versions: ['Coupe', 'Convertible', 'Competition', 'CSL'] },
    'M5': { versions: ['Sedan', 'Touring', 'Competition'] },
    'M8': { versions: ['Coupe', 'Convertible', 'Gran Coupe', 'Competition'] },
    'iX': { versions: ['xDrive40', 'xDrive50', 'M60'] },
    'iX1': { versions: ['xDrive30'] },
    'i4': { versions: ['eDrive35', 'eDrive40', 'M50'] },
    'i5': { versions: ['eDrive40', 'M60'] },
    'i7': { versions: ['eDrive50', 'xDrive60', 'M70'] },
    'iX3': { versions: ['Inspiring', 'Impressive', 'M Sport'] },
    'X3 M': { versions: ['Competition'] },
    'X4 M': { versions: ['Competition'] },
    'M2 CS': { versions: ['Standard'] },
  },
  'BYD': {
    'Atto 3': { versions: ['Comfort', 'Design'] },
    'Han': { versions: ['EV'] },
    'Tang': { versions: ['EV'] },
    'Seal': { versions: ['Design', 'Excellence', 'Performance'] },
    'Dolphin': { versions: ['Active', 'Comfort', 'Design'] },
    'Seal U': { versions: ['Comfort', 'Design'] },
  },
  'Citroën': {
    'C3': { versions: ['Live', 'Feel', 'Shine', 'Aircross'] },
    'C4': { versions: ['Feel', 'Shine', 'ë-C4'] },
    'C5 X': { versions: ['Feel', 'Shine', 'PHEV'] },
    'C5 Aircross': { versions: ['Feel', 'Shine', 'PHEV'] },
    'Berlingo': { versions: ['Live', 'Feel', 'XL'] },
  },
  'Cupra': {
    'Formentor': { versions: ['V', 'VZ', 'VZe'] },
    'Born': { versions: ['V', 'VZ'] },
    'Leon': { versions: ['V', 'VZ', 'Sportstourer'] },
    'Ateca': { versions: ['V', 'VZ'] },
    'Tavascan': { versions: ['Endurance', 'Extreme'] },
  },
  'Dacia': {
    'Sandero': { versions: ['Essential', 'Expression', 'Extreme', 'Stepway'] },
    'Duster': { versions: ['Essential', 'Expression', 'Extreme', 'Journey'] },
    'Jogger': { versions: ['Essential', 'Expression', 'Extreme', 'Hybrid'] },
    'Spring': { versions: ['Essential', 'Expression', 'Extreme'] },
  },
  'DS': {
    'DS 3': { versions: ['Bastille+', 'Rivoli+', 'Performance Line+'] },
    'DS 4': { versions: ['Bastille+', 'Rivoli+', 'Performance Line+', 'PHEV'] },
    'DS 7': { versions: ['Bastille+', 'Rivoli+', 'Performance Line+', 'PHEV'] },
    'DS 9': { versions: ['Rivoli+', 'Performance Line+'] },
  },
  'Ferrari': {
    '296 GTB': { versions: ['Standard', 'Assetto Fiorano'] },
    '296 GTS': { versions: ['Standard', 'Assetto Fiorano'] },
    'SF90': { versions: ['Stradale', 'Spider', 'XX'] },
    'Roma': { versions: ['Coupe', 'Spider'] },
    'Roma Spider': { versions: ['Standard', 'Assetto Fiorano'] },
    'Purosangue': { versions: ['Standard'] },
    '812': { versions: ['Superfast', 'GTS', 'Competizione'] },
  },
  'Fiat': {
    '500': { versions: ['Pop', 'Lounge', 'Sport', 'Dolcevita'] },
    '500e': { versions: ['Action', 'Passion', 'Icon', 'La Prima'] },
    'Panda': { versions: ['Pop', 'Lounge', 'Cross', 'City Cross'] },
    'Tipo': { versions: ['City Life', 'Life', 'Cross'] },
    '500X': { versions: ['Urban', 'Cross', 'Sport'] },
    'Ducato': { versions: ['Base', 'Maxi'] },
  },
  'Ford': {
    'Fiesta': { versions: ['Trend', 'Titanium', 'ST-Line', 'Active', 'ST'] },
    'Focus': { versions: ['Trend', 'Titanium', 'ST-Line', 'Active', 'ST'] },
    'Puma': { versions: ['Titanium', 'ST-Line', 'ST-Line X', 'ST'] },
    'Kuga': { versions: ['Titanium', 'ST-Line', 'ST-Line X', 'Vignale', 'PHEV'] },
    'Mustang': { versions: ['EcoBoost', 'GT', 'Mach 1', 'Dark Horse'] },
    'Mustang Mach-E': { versions: ['Standard', 'Extended Range', 'GT'] },
    'Ranger': { versions: ['XL', 'XLT', 'Limited', 'Wildtrak', 'Raptor'] },
    'Explorer': { versions: ['Base', 'ST-Line'] },
    'Bronco': { versions: ['Base', 'Big Bend', 'Badlands', 'Wildtrak'] },
    'Transit': { versions: ['Base', 'Trend', 'Limited'] },
  },
  'Genesis': {
    'G70': { versions: ['Standard', 'Sport'] },
    'G80': { versions: ['Standard', 'Sport', 'EV'] },
    'G90': { versions: ['Standard', 'Long'] },
    'GV60': { versions: ['Standard', 'Performance'] },
    'GV70': { versions: ['Standard', 'Sport', 'EV'] },
    'GV80': { versions: ['Standard', 'Sport'] },
  },
  'Honda': {
    'Civic': { versions: ['Comfort', 'Elegance', 'Sport', 'Advance', 'Type R'] },
    'Jazz': { versions: ['Comfort', 'Elegance', 'Crosstar'] },
    'HR-V': { versions: ['Comfort', 'Elegance', 'Advance'] },
    'CR-V': { versions: ['Comfort', 'Elegance', 'Advance', 'PHEV'] },
    'ZR-V': { versions: ['Sport', 'Advance'] },
    'e:Ny1': { versions: ['Elegance', 'Advance'] },
  },
  'Hyundai': {
    'i10': { versions: ['Pure', 'Select', 'Trend', 'Style', 'N Line'] },
    'i20': { versions: ['Pure', 'Select', 'Trend', 'Style', 'N Line', 'N'] },
    'i30': { versions: ['Pure', 'Select', 'Trend', 'Style', 'N Line', 'N'] },
    'Tucson': { versions: ['Pure', 'Select', 'Trend', 'Style', 'N Line', 'PHEV'] },
    'Kona': { versions: ['Pure', 'Select', 'Trend', 'Style', 'N Line', 'EV'] },
    'Bayon': { versions: ['Pure', 'Select', 'Trend', 'Style'] },
    'Ioniq 5': { versions: ['Standard', 'Long Range', 'AWD', 'N'] },
    'Ioniq 6': { versions: ['Standard', 'Long Range', 'AWD'] },
    'Santa Fe': { versions: ['Select', 'Trend', 'Style', 'PHEV'] },
  },
  'Ineos': {
    'Grenadier': { versions: ['Utility Wagon', 'Fieldmaster', 'Trialmaster', 'Station Wagon', 'Pickup'] },
  },
  'Jaguar': {
    'F-Pace': { versions: ['S', 'SE', 'HSE', 'R-Dynamic', 'SVR'] },
    'E-Pace': { versions: ['S', 'SE', 'HSE', 'R-Dynamic'] },
    'I-Pace': { versions: ['S', 'SE', 'HSE'] },
    'F-Type': { versions: ['Coupe', 'Convertible', 'R-Dynamic', 'R', 'SVR'] },
  },
  'Jeep': {
    'Renegade': { versions: ['Sport', 'Longitude', 'Limited', 'Trailhawk', '4xe'] },
    'Compass': { versions: ['Sport', 'Longitude', 'Limited', 'Trailhawk', '4xe'] },
    'Wrangler': { versions: ['Sport', 'Sahara', 'Rubicon', '4xe'] },
    'Grand Cherokee': { versions: ['Limited', 'Summit', 'Overland', 'Trailhawk', '4xe'] },
    'Avenger': { versions: ['Longitude', 'Altitude', 'Summit'] },
  },
  'Rivian': {
    'R1T': { versions: ['Dual-Motor', 'Performance Dual-Motor', 'Quad-Motor', 'Adventure'] },
    'R1S': { versions: ['Dual-Motor', 'Performance Dual-Motor', 'Quad-Motor', 'Adventure'] },
  },
  'Kia': {
    'Picanto': { versions: ['Concept', 'Dream', 'Spirit', 'GT-Line'] },
    'Rio': { versions: ['Concept', 'Dream', 'Spirit', 'GT-Line'] },
    'Ceed': { versions: ['Concept', 'Dream', 'Spirit', 'GT-Line', 'GT'] },
    'ProCeed': { versions: ['Dream', 'Spirit', 'GT-Line', 'GT'] },
    'Sportage': { versions: ['Concept', 'Dream', 'Spirit', 'GT-Line', 'PHEV'] },
    'EV6': { versions: ['Standard', 'Long Range', 'AWD', 'GT-Line', 'GT'] },
    'EV9': { versions: ['Standard', 'Long Range', 'GT-Line'] },
    'Niro': { versions: ['HEV', 'PHEV', 'EV'] },
    'Sorento': { versions: ['Dream', 'Spirit', 'Platinum', 'PHEV'] },
  },
  'Lamborghini': {
    'Huracán': { versions: ['EVO', 'STO', 'Tecnica', 'Sterrato'] },
    'Urus': { versions: ['S', 'Performante', 'SE', 'Urus S', 'Urus Performante'] },
    'Revuelto': { versions: ['Standard'] },
  },
  'Land Rover': {
    'Defender': { versions: ['90', '110', '130', 'V8', 'X-Dynamic', 'X'] },
    'Discovery': { versions: ['S', 'SE', 'HSE', 'R-Dynamic'] },
    'Discovery Sport': { versions: ['S', 'SE', 'HSE', 'R-Dynamic'] },
    'Range Rover': { versions: ['SE', 'HSE', 'Autobiography', 'SV', 'PHEV'] },
    'Range Rover Sport': { versions: ['SE', 'HSE', 'Autobiography', 'SVR', 'PHEV'] },
    'Range Rover Velar': { versions: ['S', 'SE', 'HSE', 'R-Dynamic'] },
    'Evoque': { versions: ['S', 'SE', 'HSE', 'R-Dynamic', 'Autobiography'] },
  },
  'Lexus': {
    'UX': { versions: ['250h', '300e'] },
    'NX': { versions: ['250', '350h', '450h+'] },
    'RX': { versions: ['350h', '450h+', '500h'] },
    'RZ': { versions: ['300e', '450e'] },
    'ES': { versions: ['300h'] },
    'IS': { versions: ['300h', '500'] },
    'LC': { versions: ['500', '500h'] },
    'LBX': { versions: ['Elegant', 'Emotion', 'Cool'] },
  },
  'Lucid': {
    'Air': { versions: ['Pure', 'Touring', 'Grand Touring', 'Sapphire'] },
    'Gravity': { versions: ['Touring', 'Grand Touring'] },
  },
  'Maserati': {
    'Ghibli': { versions: ['GT', 'Modena', 'Trofeo'] },
    'Levante': { versions: ['GT', 'Modena', 'Trofeo'] },
    'Quattroporte': { versions: ['GT', 'Modena', 'Trofeo'] },
    'MC20': { versions: ['Coupe', 'Cielo'] },
    'Grecale': { versions: ['GT', 'Modena', 'Trofeo', 'Folgore'] },
    'GranTurismo': { versions: ['Modena', 'Trofeo', 'Folgore'] },
  },
  'Mazda': {
    'Mazda2': { versions: ['Prime-Line', 'Center-Line', 'Selection'] },
    'Mazda3': { versions: ['Prime-Line', 'Selection', 'Sportback', 'Sedan'] },
    'CX-30': { versions: ['Prime-Line', 'Selection', 'Homura', 'Takumi'] },
    'CX-5': { versions: ['Prime-Line', 'Exclusive-Line', 'Homura', 'Signature'] },
    'CX-60': { versions: ['Prime-Line', 'Exclusive-Line', 'Homura', 'Takumi', 'PHEV'] },
    'CX-80': { versions: ['Exclusive-Line', 'Homura', 'Takumi'] },
    'MX-5': { versions: ['Prime-Line', 'Exclusive-Line', 'Homura', 'RF'] },
  },
  'McLaren': {
    '750S': { versions: ['Coupe', 'Spider'] },
    'Artura': { versions: ['Standard', 'Spider'] },
    'GT': { versions: ['Standard'] },
  },
  'Mercedes-Benz': {
    'A-Class': { versions: ['Style', 'AMG Line', 'Progressive', 'A35 AMG', 'A45 AMG'] },
    'B-Class': { versions: ['Style', 'AMG Line', 'Progressive'] },
    'C-Class': { versions: ['Sedan', 'Estate', 'Avantgarde', 'AMG Line', 'C43 AMG', 'C63 AMG'] },
    'E-Class': { versions: ['Sedan', 'Estate', 'Avantgarde', 'AMG Line', 'E53 AMG'] },
    'S-Class': { versions: ['Standard', 'Long', 'AMG Line', 'Maybach'] },
    'CLA': { versions: ['Coupe', 'Shooting Brake', 'AMG Line', 'CLA35 AMG', 'CLA45 AMG'] },
    'GLA': { versions: ['Style', 'AMG Line', 'GLA35 AMG', 'GLA45 AMG'] },
    'GLB': { versions: ['Style', 'AMG Line', 'GLB35 AMG'] },
    'GLC': { versions: ['Standard', 'Coupe', 'AMG Line', 'GLC43 AMG', 'GLC63 AMG'] },
    'GLE': { versions: ['Standard', 'Coupe', 'AMG Line', 'GLE53 AMG', 'GLE63 AMG'] },
    'GLS': { versions: ['Standard', 'AMG Line', 'GLS63 AMG', 'Maybach'] },
    'G-Class': { versions: ['G500', 'AMG G63'] },
    'AMG GT': { versions: ['43', '53', '63', '63 S'] },
    'EQA': { versions: ['250', '250+', '300', '350'] },
    'EQB': { versions: ['250+', '300', '350'] },
    'EQE': { versions: ['300', '350+', '500', 'AMG'] },
    'EQS': { versions: ['350+', '450+', '580', 'AMG', 'SUV'] },
    'V-Class': { versions: ['Standard', 'Long', 'Extra Long', 'AMG Line'] },
  },
  'MG': {
    'MG4': { versions: ['Standard', 'Comfort', 'Luxury', 'Trophy', 'XPower'] },
    'ZS': { versions: ['Standard', 'Comfort', 'Luxury', 'EV'] },
    'HS': { versions: ['Standard', 'Comfort', 'Luxury', 'PHEV'] },
    'MG5': { versions: ['Standard', 'Luxury', 'Long Range'] },
    'Cyberster': { versions: ['Standard', 'Trophy'] },
  },
  'Mini': {
    'Cooper': { versions: ['Classic', 'Sport', 'Exclusive', 'S', 'JCW'] },
    'Countryman': { versions: ['Classic', 'Sport', 'Exclusive', 'S', 'JCW', 'SE'] },
    'Clubman': { versions: ['Classic', 'Sport', 'Exclusive', 'S', 'JCW'] },
    'Aceman': { versions: ['E', 'SE'] },
  },
  'Nissan': {
    'Micra': { versions: ['Visia', 'Acenta', 'N-Connecta', 'Tekna'] },
    'Juke': { versions: ['Visia', 'Acenta', 'N-Connecta', 'Tekna', 'Nismo'] },
    'Qashqai': { versions: ['Visia', 'Acenta', 'N-Connecta', 'Tekna', 'e-Power'] },
    'X-Trail': { versions: ['Acenta', 'N-Connecta', 'Tekna', 'e-Power', 'e-4ORCE'] },
    'Leaf': { versions: ['Acenta', 'N-Connecta', 'Tekna', 'e+'] },
    'Ariya': { versions: ['Advance', 'Evolve', 'Evolve+', 'e-4ORCE'] },
  },
  'Opel': {
    'Corsa': { versions: ['Edition', 'Elegance', 'GS Line', 'GS', 'Electric'] },
    'Astra': { versions: ['Edition', 'Elegance', 'GS Line', 'GS', 'PHEV', 'Sports Tourer'] },
    'Mokka': { versions: ['Edition', 'Elegance', 'GS Line', 'GS', 'Electric'] },
    'Grandland': { versions: ['Edition', 'Elegance', 'GS Line', 'GS', 'PHEV'] },
  },
  'Peugeot': {
    '208': { versions: ['Active', 'Allure', 'GT', 'GT Pack', 'e-208'] },
    '308': { versions: ['Active', 'Allure', 'GT', 'GT Pack', 'PHEV'] },
    '408': { versions: ['Allure', 'GT', 'PHEV'] },
    '508': { versions: ['Active', 'Allure', 'GT', 'GT Pack', 'SW', 'PHEV'] },
    '2008': { versions: ['Active', 'Allure', 'GT', 'e-2008'] },
    '3008': { versions: ['Active', 'Allure', 'GT', 'GT Pack', 'PHEV'] },
    '5008': { versions: ['Active', 'Allure', 'GT'] },
  },
  'Polestar': {
    'Polestar 2': { versions: ['Standard', 'Long Range', 'Performance'] },
    'Polestar 3': { versions: ['Long Range', 'Performance'] },
    'Polestar 4': { versions: ['Long Range', 'Performance'] },
  },
  'Porsche': {
    '911': { versions: ['Carrera', 'Carrera S', 'Carrera 4', 'Carrera 4S', 'Carrera GTS', 'Targa 4', 'Targa 4S', 'Turbo', 'Turbo S', 'GT3', 'GT3 RS', 'Dakar', 'S/T'] },
    'Cayenne': { versions: ['Standard', 'S', 'E-Hybrid', 'GTS', 'Turbo GT', 'Coupe'] },
    'Macan': { versions: ['Standard', 'S', 'GTS', 'Turbo', 'Electric'] },
    'Panamera': { versions: ['Standard', 'S', 'E-Hybrid', 'GTS', 'Turbo', 'Sport Turismo'] },
    'Taycan': { versions: ['Standard', '4S', 'GTS', 'Turbo', 'Turbo S', 'Cross Turismo'] },
    '718 Boxster': { versions: ['Standard', 'S', 'GTS', 'Spyder'] },
    '718 Cayman': { versions: ['Standard', 'S', 'GTS', 'GT4', 'GT4 RS'] },
  },
  'Renault': {
    'Clio': { versions: ['Life', 'Zen', 'Intens', 'RS Line', 'Initiale Paris', 'E-Tech'] },
    'Captur': { versions: ['Life', 'Zen', 'Intens', 'RS Line', 'E-Tech', 'PHEV'] },
    'Megane E-Tech': { versions: ['Equilibre', 'Techno', 'Iconic'] },
    'Arkana': { versions: ['Zen', 'Intens', 'RS Line', 'E-Tech'] },
    'Austral': { versions: ['Equilibre', 'Techno', 'Iconic', 'Esprit Alpine'] },
    'Scenic E-Tech': { versions: ['Equilibre', 'Techno', 'Iconic', 'Esprit Alpine'] },
    'R5 E-Tech': { versions: ['Urban Range', 'Comfort Range', 'Long Range'] },
  },
  'Rolls-Royce': {
    'Ghost': { versions: ['Standard', 'Extended', 'Black Badge'] },
    'Phantom': { versions: ['Standard', 'Extended'] },
    'Cullinan': { versions: ['Standard', 'Black Badge'] },
    'Spectre': { versions: ['Standard'] },
  },
  'Seat': {
    'Ibiza': { versions: ['Reference', 'Style', 'Xcellence', 'FR'] },
    'Leon': { versions: ['Reference', 'Style', 'Xcellence', 'FR', 'Sportstourer'] },
    'Arona': { versions: ['Reference', 'Style', 'Xcellence', 'FR'] },
    'Ateca': { versions: ['Style', 'Xcellence', 'FR'] },
  },
  'Škoda': {
    'Fabia': { versions: ['Active', 'Ambition', 'Style', 'Monte Carlo'] },
    'Octavia': { versions: ['Active', 'Ambition', 'Style', 'L&K', 'RS', 'Combi'] },
    'Superb': { versions: ['Active', 'Ambition', 'Style', 'L&K', 'Combi'] },
    'Kamiq': { versions: ['Active', 'Ambition', 'Style', 'Monte Carlo'] },
    'Karoq': { versions: ['Active', 'Ambition', 'Style', 'Sportline'] },
    'Kodiaq': { versions: ['Active', 'Ambition', 'Style', 'L&K', 'Sportline', 'RS'] },
    'Enyaq': { versions: ['60', '80', '80x', 'RS', 'Coupe'] },
  },
  'Subaru': {
    'Impreza': { versions: ['Comfort', 'Style', 'Platinum'] },
    'Crosstrek': { versions: ['Comfort', 'Style', 'Platinum'] },
    'Forester': { versions: ['Comfort', 'Style', 'Platinum', 'Sport'] },
    'Outback': { versions: ['Comfort', 'Style', 'Platinum', 'Field'] },
    'Solterra': { versions: ['Comfort', 'Style', 'Platinum'] },
    'BRZ': { versions: ['Sport', 'Premium'] },
    'WRX': { versions: ['Standard', 'STI'] },
  },
  'Suzuki': {
    'Swift': { versions: ['Club', 'Compact+', 'Hybrid', 'Sport'] },
    'Ignis': { versions: ['Club', 'Compact+'] },
    'Vitara': { versions: ['Club', 'Compact+', 'Flash'] },
    'S-Cross': { versions: ['Club', 'Compact+', 'Flash'] },
    'Jimny': { versions: ['Standard'] },
  },
  'Tesla': {
    'Model 3': { versions: ['Standard Range', 'Long Range', 'Performance', 'Highland'] },
    'Model Y': { versions: ['Standard Range', 'Long Range', 'Performance'] },
    'Model S': { versions: ['Standard', 'Plaid'] },
    'Model X': { versions: ['Standard', 'Plaid'] },
    'Cybertruck': { versions: ['Single Motor', 'Dual Motor', 'Tri Motor', 'Cyberbeast'] },
  },
  'Toyota': {
    'Yaris': { versions: ['Active', 'Comfort', 'Lounge', 'GR Sport', 'GR'] },
    'Yaris Cross': { versions: ['Active', 'Comfort', 'Lounge', 'GR Sport'] },
    'Corolla': { versions: ['Active', 'Comfort', 'Lounge', 'GR Sport', 'Touring Sports'] },
    'Corolla Cross': { versions: ['Active', 'Comfort', 'Lounge'] },
    'Camry': { versions: ['Comfort', 'Lounge'] },
    'RAV4': { versions: ['Active', 'Comfort', 'Lounge', 'GR Sport', 'PHEV'] },
    'C-HR': { versions: ['Active', 'Comfort', 'Lounge', 'GR Sport'] },
    'Highlander': { versions: ['Comfort', 'Lounge', 'Executive'] },
    'Supra': { versions: ['Pure', 'Prominent', 'GR'] },
    'GR86': { versions: ['Standard', 'Premium'] },
    'Land Cruiser': { versions: ['Standard', 'Comfort', 'Lounge', 'GR Sport'] },
    'Hilux': { versions: ['Active', 'Comfort', 'Style', 'GR Sport'] },
    'bZ4X': { versions: ['Active', 'Comfort', 'Lounge'] },
  },
  'Volkswagen': {
    'Polo': { versions: ['Life', 'Style', 'R-Line', 'GTI'] },
    'Golf': { versions: ['Life', 'Style', 'R-Line', 'GTI', 'GTD', 'GTE', 'R'] },
    'Passat': { versions: ['Business', 'Elegance', 'R-Line', 'Variant', 'GTE'] },
    'Arteon': { versions: ['Elegance', 'R-Line', 'Shooting Brake', 'R'] },
    'Tiguan': { versions: ['Life', 'Elegance', 'R-Line', 'eHybrid', 'R'] },
    'T-Roc': { versions: ['Life', 'Style', 'R-Line', 'Cabriolet', 'R'] },
    'T-Cross': { versions: ['Life', 'Style', 'R-Line'] },
    'Touareg': { versions: ['Elegance', 'Atmosphere', 'R-Line', 'R', 'eHybrid'] },
    'Taigo': { versions: ['Life', 'Style', 'R-Line'] },
    'ID.3': { versions: ['Pure', 'Pro', 'Pro S', 'GTX'] },
    'ID.4': { versions: ['Pure', 'Pro', 'Pro S', 'GTX'] },
    'ID.5': { versions: ['Pro', 'Pro S', 'GTX'] },
    'ID.7': { versions: ['Pro', 'Pro S', 'GTX', 'Tourer'] },
    'ID.Buzz': { versions: ['Pro', 'Pro S', 'GTX', 'LWB'] },
    'Caddy': { versions: ['Base', 'Life', 'Style', 'Maxi'] },
    'Multivan': { versions: ['Life', 'Style', 'Energetic', 'eHybrid'] },
    'Transporter': { versions: ['Base', 'Business', 'Caravelle'] },
    'Amarok': { versions: ['Life', 'Style', 'PanAmericana', 'Aventura'] },
  },
  'Mitsubishi': {
    'Space Star': { versions: ['Inform', 'Invite', 'Intense', 'Spirit'] },
    'ASX': { versions: ['Inform', 'Invite', 'Intense', 'Spirit', 'PHEV'] },
    'Eclipse Cross': { versions: ['Inform', 'Invite', 'Intense', 'PHEV'] },
    'Outlander': { versions: ['Inform', 'Invite', 'Intense', 'Instyle', 'PHEV'] },
    'L200': { versions: ['Inform', 'Invite', 'Intense', 'Spirit'] },
  },
  'Smart': {
    'fortwo': { versions: ['Pure', 'Passion', 'Prime', 'EQ'] },
    'forfour': { versions: ['Pure', 'Passion', 'Prime', 'EQ'] },
    '#1': { versions: ['Pro+', 'Premium', 'BRABUS'] },
    '#3': { versions: ['Pro+', 'Premium', 'BRABUS'] },
  },
  'Lancia': {
    'Ypsilon': { versions: ['Base', 'Cassina', 'Edizione Limitata'] },
  },
  'SsangYong': {
    'Tivoli': { versions: ['Crystal', 'Sapphire', 'Diamond'] },
    'Korando': { versions: ['Crystal', 'Sapphire', 'Diamond', 'e-Motion'] },
    'Rexton': { versions: ['Sapphire', 'Diamond'] },
    'Torres': { versions: ['Base', 'Premium', 'EVX'] },
  },
  'Volvo': {
    'XC40': { versions: ['Core', 'Plus', 'Ultimate', 'Recharge'] },
    'XC60': { versions: ['Core', 'Plus', 'Ultimate', 'Polestar'] },
    'XC90': { versions: ['Core', 'Plus', 'Ultimate', 'Recharge'] },
    'S60': { versions: ['Core', 'Plus', 'Ultimate', 'Polestar'] },
    'S90': { versions: ['Core', 'Plus', 'Ultimate'] },
    'V60': { versions: ['Core', 'Plus', 'Ultimate', 'Cross Country', 'Polestar'] },
    'V90': { versions: ['Core', 'Plus', 'Ultimate', 'Cross Country'] },
    'C40': { versions: ['Core', 'Plus', 'Ultimate'] },
    'EX30': { versions: ['Core', 'Plus', 'Ultra', 'Performance'] },
    'EX90': { versions: ['Core', 'Plus', 'Ultra', 'Performance'] },
  },
}

export const CAR_MAKE_LIST = Object.keys(CAR_MAKES_MODELS).sort()

export function getModelList(make: string): string[] {
  const models = CAR_MAKES_MODELS[make]
  return models ? Object.keys(models).sort() : []
}

export function getVersionList(make: string, model: string): string[] {
  const models = CAR_MAKES_MODELS[make]
  if (!models) return []
  const info = models[model]
  return info ? info.versions : []
}

export const FUEL_TYPES = [
  'Petrol', 'Diesel', 'Electric', 'Hybrid (Petrol)', 'Hybrid (Diesel)',
  'Plug-in Hybrid (PHEV)', 'Natural Gas (CNG)', 'LPG', 'Hydrogen',
] as const

export const SWISS_VAT_RATE = 0.081
export const DEFAULT_PREP_FEE_CHF = 380

export interface CatalogItem {
  artNr: string
  name: string
  unit: string
  unitPriceCents: number
  category: 'PART' | 'SERVICE'
}

export const WORKSHOP_CATALOG: CatalogItem[] = [
  // Services
  { artNr: '01', name: 'Mechanic Labor', unit: 'hr', unitPriceCents: 21500, category: 'SERVICE' },
  { artNr: '55', name: 'Spring Check', unit: 'pc', unitPriceCents: 6900, category: 'SERVICE' },
  { artNr: '06', name: 'Tire Change incl. Balancing', unit: 'pc', unitPriceCents: 4000, category: 'SERVICE' },
  { artNr: '764', name: 'Tire Storage (Season)', unit: 'pc', unitPriceCents: 4000, category: 'SERVICE' },
  { artNr: '12', name: 'Tire Disposal', unit: 'pc', unitPriceCents: 650, category: 'SERVICE' },
  { artNr: '74G', name: 'Exterior Wash', unit: 'pc', unitPriceCents: 3500, category: 'SERVICE' },
  { artNr: '75G', name: 'Interior Cleaning', unit: 'pc', unitPriceCents: 4500, category: 'SERVICE' },
  { artNr: 'SC', name: 'Wiper Blade Replacement', unit: 'pc', unitPriceCents: 2000, category: 'SERVICE' },
  { artNr: 'OW', name: 'Oil Change', unit: 'pc', unitPriceCents: 8000, category: 'SERVICE' },
  { artNr: 'MFK', name: 'Technical Inspection (MFK)', unit: 'pc', unitPriceCents: 5000, category: 'SERVICE' },
  { artNr: 'CL', name: 'Full Detail (Interior + Exterior)', unit: 'pc', unitPriceCents: 12000, category: 'SERVICE' },
  { artNr: 'MW', name: 'Rental Car', unit: 'day', unitPriceCents: 4900, category: 'SERVICE' },
  { artNr: 'BS', name: 'Brake Service (per axle)', unit: 'pc', unitPriceCents: 18000, category: 'SERVICE' },
  { artNr: 'AC', name: 'A/C Service & Recharge', unit: 'pc', unitPriceCents: 15000, category: 'SERVICE' },
  { artNr: 'WA', name: 'Wheel Alignment', unit: 'pc', unitPriceCents: 12000, category: 'SERVICE' },
  { artNr: 'BI', name: 'Battery Inspection & Replacement', unit: 'pc', unitPriceCents: 5000, category: 'SERVICE' },
  { artNr: 'DG', name: 'Diagnostic Scan', unit: 'pc', unitPriceCents: 8500, category: 'SERVICE' },
  { artNr: 'SP', name: 'Spark Plug Replacement', unit: 'pc', unitPriceCents: 6000, category: 'SERVICE' },
  { artNr: 'CF', name: 'Coolant Flush', unit: 'pc', unitPriceCents: 9500, category: 'SERVICE' },
  { artNr: 'TF', name: 'Transmission Fluid Change', unit: 'pc', unitPriceCents: 14000, category: 'SERVICE' },
  { artNr: 'FL', name: 'Headlight / Taillight Replacement', unit: 'pc', unitPriceCents: 4500, category: 'SERVICE' },
  // Parts
  { artNr: '07', name: 'Summer Tire', unit: 'pc', unitPriceCents: 35300, category: 'PART' },
  { artNr: '08', name: 'Winter Tire', unit: 'pc', unitPriceCents: 35300, category: 'PART' },
  { artNr: '09', name: 'All-Season Tire', unit: 'pc', unitPriceCents: 32000, category: 'PART' },
  { artNr: '400', name: 'Engine Oil (Motorex)', unit: 'L', unitPriceCents: 2500, category: 'PART' },
  { artNr: '401', name: 'Engine Oil (Castrol Edge)', unit: 'L', unitPriceCents: 2800, category: 'PART' },
  { artNr: '402', name: 'Engine Oil (Mobil 1)', unit: 'L', unitPriceCents: 3000, category: 'PART' },
  { artNr: 'KN', name: 'K&N Air Filter', unit: 'pc', unitPriceCents: 6500, category: 'PART' },
  { artNr: 'OF', name: 'Oil Filter', unit: 'pc', unitPriceCents: 2500, category: 'PART' },
  { artNr: 'CF', name: 'Cabin Air Filter', unit: 'pc', unitPriceCents: 3500, category: 'PART' },
  { artNr: 'WB', name: 'Wiper Blade Set', unit: 'pair', unitPriceCents: 4500, category: 'PART' },
  { artNr: '104', name: 'Antifreeze / Coolant', unit: 'L', unitPriceCents: 1435, category: 'PART' },
  { artNr: '105', name: 'Windshield Washer Fluid', unit: 'pc', unitPriceCents: 680, category: 'PART' },
  { artNr: 'BP', name: 'Brake Pads (Front)', unit: 'set', unitPriceCents: 12000, category: 'PART' },
  { artNr: 'BPR', name: 'Brake Pads (Rear)', unit: 'set', unitPriceCents: 10000, category: 'PART' },
  { artNr: 'BD', name: 'Brake Disc (Front)', unit: 'pc', unitPriceCents: 15000, category: 'PART' },
  { artNr: 'BDR', name: 'Brake Disc (Rear)', unit: 'pc', unitPriceCents: 13000, category: 'PART' },
  { artNr: 'BT', name: 'Battery (Standard)', unit: 'pc', unitPriceCents: 18000, category: 'PART' },
  { artNr: 'SPK', name: 'Spark Plug', unit: 'pc', unitPriceCents: 1800, category: 'PART' },
  { artNr: '400R', name: 'Ragazzon Flex Pipe incl. Center Silencer', unit: 'pc', unitPriceCents: 78900, category: 'PART' },
  { artNr: '400V', name: 'Connecting Pipe', unit: 'pc', unitPriceCents: 8890, category: 'PART' },
  { artNr: 'KR', name: 'Small Parts & Cleaning Supplies', unit: 'pc', unitPriceCents: 1275, category: 'PART' },
  { artNr: 'HL', name: 'Headlight Bulb (H7/H4)', unit: 'pc', unitPriceCents: 2200, category: 'PART' },
  { artNr: 'TB', name: 'Timing Belt', unit: 'pc', unitPriceCents: 8500, category: 'PART' },
]

export const DURATION_OPTIONS = [12, 24, 36, 48, 60] as const
